services:
  - type: web
    name: slidevault
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
